---
- name: Install Nagios (Ubuntu)
  tags: ubuntu, nagios
  apt:
    name: nagios4
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install Prerequisites (CentOS)
  tags: prereq, centos
  package:
    name:
      - httpd
      - php
      - php-cli
      - gcc
      - glibc
      - gd
      - net-snmp
      - openssl-devel
      - wget
      - unzip
      - epel-release
    state: latest
  when: ansible_distribution == "CentOS"

- name: Install Nagios (CentOS)
  tags: nagios, centos
  yum:
    name: nagios
    state: latest
  when: ansible_distribution == "CentOS"
